---

- hosts: all
  become: true
  tasks:

  - name: install apache2 ,php and update 
    package:
     name:
       -  "{{apache_package}}"
       -  "{{php_package}}"
     state: latest
     update_cache: yes
    # state: absent
   # when: ansible_distribution in [ "Ubuntu","Debian"]


