---

- hosts: all
  become: true
  tasks:

  - name: update repository index for Ubuntu
    apt:
      update_cache: yes

  - name: install apache2 package on Ubuntu
    apt:
      name: apache2
      state: latest

  - name: install php package on Ubuntu
    apt:
      name: libapache2-mod-php
      state: latest
