---

- hosts: all
  become: true
  tasks:

#  - name: update repository index for Ubuntu
#    apt:
#     update_cache: yes
#    when: ansible_distribution == "Ubuntu"
#
#  - name: install apache2 and php packages for ubuntu
#    apt:
#     name:
#       -  apache2
#       -  libapache2-mod-php
#     state: latest
#    # state: absent
#
#    when: ansible_distribution == "Ubuntu"
#   # when: ansible_distribution in [ "Ubuntu","Debian"]


  - name: update repository index for CentOS
    yum:
     update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install apache & php package for CentOS
    yum:
     name:
       -  httpd
       -  php
     state: latest
    # state: absent

    when: ansible_distribution == "CentOS"
   # when: ansible_distribution in [ "Ubuntu","Debian"]

